#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Update modified date for published posts
git diff --cached --name-status | grep -i '^M.*\.md$' | while read _ file; do
  if [[ "$file" == src/data/blog/* ]]; then
    filecontent=$(cat "$file")
    frontmatter=$(echo "$filecontent" | awk -v RS='---' 'NR==2{print}')
    draft=$(echo "$frontmatter" | awk '/^draft: /{print $2}')
    
    if [ "$draft" = "false" ]; then
      echo "Updating modDatetime for: $file"
      sed -i "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file"
      git add "$file"
    fi
  fi
done

# Set pubDatetime for new posts
git diff --cached --name-status | grep -i '^A.*\.md$' | while read _ file; do
  if [[ "$file" == src/data/blog/* ]]; then
    echo "Setting pubDatetime for: $file"
    sed -i "/---.*/,/---.*/s/^pubDatetime:.*$/pubDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file"
    git add "$file"
  fi
done
